try to keep libzstd.a "as is" once created
facebook/zstd pull request #2438
Opened 2020-12-21 01:13 UTC by Cyan4973

to be compatible with scenarios such as `make -j allmost`.
May help #2436

2020-12-21 17:28 UTC, terrelln approved these changes

2020-12-21 17:29 UTC, terrelln requested changes
Tests are failing

2020-12-22 00:30 UTC, Cyan4973 commented
All tests fixed.
Remaining ones are failing independently of this PR.
32-bit test is fixed in #2440.
Fuzzing + msan has been failing for a while now,
I may disable it on short term so that we stop considering "normal" to have red failures in CI.

2020-12-22 01:21 UTC, Cyan4973 commented
Actually, disabling fuzzing + msan seems more difficult than anticipated,
as it seems to be a [runtime issue (time out)](https://github.com/facebook/zstd/pull/2438/checks?check_run_id=1592001475#step:5:11),
but the script controllling _all_ fuzzing jobs seems controlled from `oss-fuzz` : 
https://github.com/facebook/zstd/blob/dev/.github/workflows/main.yml#L18 ,
so there is no obvious way to fix it, nor to opt out selectively from msan tests (but keep the rest running)
and I'm reluctant about removing all `oss-fuzz` tests on the ground that the `msan` variant is flackey.

2020-12-22 02:09 UTC, terrelln commented
I'll open an issue on oss-fuzz about the msan failure.

2020-12-22 02:11 UTC, terrelln commented
It looks like `check-32bit` test is failing, but that seems unrelated to this PR I think.

2020-12-22 02:11 UTC, terrelln approved these changes

2020-12-22 02:12 UTC, terrelln commented
https://github.com/google/oss-fuzz/issues/4879

2020-12-22 08:31 UTC, merged

2020-12-28 11:44 UTC, evverx commented
> the script controllling all fuzzing jobs seems controlled from oss-fuzz :
https://github.com/facebook/zstd/blob/dev/.github/workflows/main.yml#L18 ,
so there is no obvious way to fix it, nor to opt out selectively from msan tests (but keep the rest running)
and I'm reluctant about removing all oss-fuzz tests on the ground that the msan variant is flackey.

I think it should be possible to remove "memory" from [the "sanitizer" list](https://github.com/facebook/zstd/blob/d4f7d75f84427c7d06903d9dbecee7033f3ad47a/.github/workflows/main.yml#L9) to turn off only Msan there:
```diff
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
index 0e14345..5e5aae1 100644
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,7 +6,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        sanitizer: [address, undefined, memory]
+        sanitizer: [address, undefined]
     steps:
     - name: Build Fuzzers (${{ matrix.sanitizer }})
       id: build
```
Though I hope the issue will be fixed soon.

2020-12-28 19:17 UTC, Cyan4973 commented
That's a good point @evverx ,
we should probably do that while waiting for the issue to get fixed on `ossfuzz` side.