Enhance streaming_compression examples.
facebook/zstd pull request #2813
Opened 2021-10-04 06:25 UTC by marxin

Add level argument to the first test and be more verbose about
used compression level and number of threads.

2021-10-05 14:21 UTC, senhuang42 commented on examples/streaming_compression.c
> +#define THREADS 4
I don't think a macro is necessary here. You can pass a `const int nbThreads = 4` from `main()` and add an `nbThreads` arg to `compressFile_orDie`. That way it's more consistent with the change to `cLevel` getting passed from main as well (and in fact, you could add `nbThreads` as an additional arg to the CLI too).

2021-10-05 14:24 UTC, senhuang42 requested changes
Overall I like the improvement to the example! Just some minor suggestions.

2021-10-05 14:24 UTC, senhuang42 commented on examples/streaming_compression.c
> +    if (argc!=3) {
Nit: I'd prefer if we were able to keep the usage as `exeName FILE` with the optionality of specifying `exeName FILE LEVEL` and maybe even `exeName FILE LEVEL NUM_THREADS`.

2021-10-05 14:24 UTC, senhuang42 commented on examples/streaming_compression_thread_pool.c
> +    ZSTD_CCtx_setParameter(cctx, ZSTD_c_nbWorkers, THREADS);
Nit: ditto for the unnecessary macro - prefer using local `const` variable.

2021-10-05 15:27 UTC, marxin commented
Thank you for the comments, I made the suggested changes. I like your suggestions.

2021-10-11 12:52 UTC, marxin commented
@senhuang42 May I please ping this?

2021-10-11 15:30 UTC, senhuang42 approved these changes
lgtm, thanks for the update!

2021-10-11 21:50 UTC, senhuang42 commented
I see some tests are failing, can you update the base repo on top of which this branch sits to the latest dev branch and then force push onto this PR again?

2021-10-12 07:02 UTC, marxin commented
Sure, I've just done that.

2021-10-12 16:35 UTC, Cyan4973 approved these changes

2021-10-12 17:05 UTC, merged