Starting state: Sequences
facebook/zstd pull request #3910
Opened 2024-02-14 16:00 UTC by roynalnaruto

While initialising the FSE state in the Sequences section, we follow the interleaves order:
```
[..., offset, match_length, literal_length, literal_length, match_length, offset, ...]
```

This suggests there might have been a mismatch in the document?

Please close PR if I misunderstood.

2024-02-14 21:17 UTC, Cyan4973 requested changes
The specification is correct : https://github.com/facebook/zstd/blob/v1.5.5/lib/decompress/zstd_decompress_block.c#L1378

2024-02-15 21:28 UTC, roynalnaruto commented
If the specs are correct, then we can close this PR. Thank you :)

2024-02-15 21:44 UTC, roynalnaruto commented
@Cyan4973 however there is another section below that states:
```
If it is not the last sequence in the block, the next operation is to update states. Using the rules pre-calculated in the decoding tables, Literals_Length_State is updated, followed by Match_Length_State, and then Offset_State. See the [FSE section](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#fse) for details on how to update states from the bitstream.
```

Does it mean the order is incorrect here, and should instead be:
```
... Using the rules pre-calculated in the decoding tables, Literals_Length_State is updated, followed by Offset_State, and then Match_Length_State ...
```

2024-02-15 22:00 UTC, Cyan4973 commented
No, the order is correct too : 
https://github.com/facebook/zstd/blob/v1.5.5/lib/decompress/zstd_decompress_block.c#L1291

There are a few things which can be confused: 
- The spec must be understood from a decompressor point of view, with the understanding that the encoder is doing the reverse operation, hence in reverse order.
- Reading the initial FSE state values is a separated operation. It's not part of the main decoding loop, and therefore isn't constrained by the ordering inside the loop. Both operations have therefore their own order.

2024-02-16 04:25 UTC, roynalnaruto commented
So if I understand correctly:
- Initialising the FSE state (from a decoder's perspective): `LL state -> Offset state -> ML state`
- Further decoding loop: `numbits Offset -> numbits ML -> numbits LL -> update LL state -> update ML state -> update Offset state`

2024-02-16 07:19 UTC, Cyan4973 commented
Yes

2024-02-16 07:26 UTC, roynalnaruto commented
Closing as there is no issue with the original documentation

2024-02-16 07:26 UTC, closed without merging