Fixed warning when compiling pzstd with CPPFLAGS=-Wunused-result and …
facebook/zstd pull request #4134
Opened 2024-08-31 14:57 UTC by inventor500

This should close #4133.
This problem is not particularly important, since this was a build warning and does not seem to effect anything, but it does remove a warning when compiling on GCC.

2024-08-31 18:06 UTC, Cyan4973 approved these changes

2024-09-23 23:56 UTC, neheb commented
I don't think this is right. The code seems to be wanting to do https://en.wikipedia.org/wiki/Erase%E2%80%93remove_idiom

Meaning

```
--- a/contrib/pzstd/Options.cpp
+++ b/contrib/pzstd/Options.cpp
@@ -322,7 +322,7 @@ Options::Status Options::parse(int argc, const char **argv) {
   g_utilDisplayLevel = verbosity;
   // Remove local input files that are symbolic links
   if (!followLinks) {
-      std::remove_if(localInputFiles.begin(), localInputFiles.end(),
+      localInputFiles.erase(std::remove_if(localInputFiles.begin(), localInputFiles.end(),
                      [&](const char *path) {
                         bool isLink = UTIL_isLink(path);
                         if (isLink && verbosity >= 2) {
@@ -332,7 +332,7 @@ Options::Status Options::parse(int argc, const char **argv) {
                                     path);
                         }
                         return isLink;
-                    });
+                    }), localInputFiles.end());
   }
 
   // Translate input files/directories into files to (de)compress
```

is the proper solution.

It doesn't affect anything since this is contrib and not really used.

2024-09-25 14:59 UTC, terrelln requested changes
Thanks for the PR! Please make the change that @neheb is suggesting.

2024-09-25 15:51 UTC, terrelln approved these changes

2024-09-25 15:51 UTC, terrelln commented
Thanks for the bug fix @inventor500 & @neheb!

2024-09-25 16:51 UTC, merged